[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bootstrap-flask>=2.4.2",
    "flask>=3.1.0",
    "flask-wtf>=1.2.2",
    "gunicorn>=23.0.0",
]
